CREATE TABLE USERS
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(30),
    LAST_NAME  VARCHAR(30),
    EMAIL      VARCHAR(100) NOT NULL,
    PASSWORD   VARCHAR(255) NOT NULL
);
CREATE TABLE EVENT
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    FK_ORGANIZER_ID BIGINT NOT NULL,
    CONSTRAINT FK_O FOREIGN KEY (FK_ORGANIZER_ID)
        REFERENCES STATUS (ID)
);
CREATE TABLE USERS_TO_EVENTS
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    FK_USER_ID   BIGINT NOT NULL,
    FK_EVENT_ID  BIGINT NOT NULL,
    FK_STATUS_ID BIGINT NOT NULL,
    CONSTRAINT FK_UTES_TO_USERS FOREIGN KEY (FK_USER_ID)
        REFERENCES USERS (ID),
    CONSTRAINT FK_UTESI_TO_EVENT FOREIGN KEY (FK_EVENT_ID)
        REFERENCES EVENT (ID),
    CONSTRAINT FK_UTESA_TO_EVENT FOREIGN KEY (FK_STATUS_ID)
        REFERENCES STATUS (ID)
);
CREATE TABLE STATUS
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL
);
CREATE TABLE ORGANIZER
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    FK_USER_ID  BIGINT NOT NULL,
    CONSTRAINT FK_O_TO_USERS FOREIGN KEY (FK_USER_ID)
        REFERENCES USERS (ID)
);
